name: proyecto-de-ia # This will become the name of your environment
dependencies: # The list of packages to include in your environment
  - python=3.11
  - flask
  - requests
  - cudatoolkit
  - pip # Install pip in your environment
  - pip: # Include pip dependencies last
      - torch
      - torchvision
      - mod_wsgi-standalone
